implemnet drag and drop in fileinput
adobe/aem-core-forms-components pull request #1016
Opened 2023-12-18 11:20 UTC by rajatofficial

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-01-02 09:04 UTC, rismehta requested changes
check comments

2024-01-02 09:04 UTC, rismehta commented on ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
> +        it.only(`${fileInput.type} - attach files using drag and drop, check model, view, preview attachment and submit the form`, () => {
Can you remove `only` from here ?

2024-01-09 05:05 UTC, rajatofficial commented on ui.tests/test-module/specs/fileinput/fileinput.runtime.spec.js
> +        it.only(`${fileInput.type} - attach files using drag and drop, check model, view, preview attachment and submit the form`, () => {
Removed and test cases fixed.

2024-01-09 07:29 UTC, rismehta approved these changes

2024-01-09 07:29 UTC, merged