updated readme for the link of display pattern of date picker and num…
adobe/aem-core-forms-components pull request #1023
Opened 2023-12-19 06:18 UTC by egmox

…eric input

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-12-19 09:59 UTC, rismehta requested changes
check comments

2023-12-19 09:59 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/numberinput/v1/numberinput/README.md
> +15. `./displayFormat` - define the regex pattern complied with the unicode pattern (Can be found [here](https://unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns)).
unicode patterns are not regex, instead, it typically refers to a template or a set of symbols that define how dates and times should be formatted.

2023-12-19 10:41 UTC, egmox commented
@rismehta comments are resolved

2023-12-20 06:44 UTC, sakshi-arora1 approved these changes

2023-12-20 07:02 UTC, merged