re-enable RTL in 65 branch
adobe/aem-core-forms-components pull request #1125
Opened 2024-03-15 05:03 UTC by ravise5

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-03-15 05:31 UTC, devgurjar approved these changes

2024-03-15 06:48 UTC, sakshi-arora1 approved these changes

2024-03-20 10:58 UTC, rismehta requested changes
Why is this PR directly open for 650 ? Are the changes not in master ?

2024-04-17 17:51 UTC, iamsudhanshu commented
> Why is this PR directly open for 650 ? Are the changes not in master ?

Changes are already available in master, but the same had been reverted on 6.5 due to required changes not available in targeted Forms add-on during the release of the core-components.

2024-04-17 18:00 UTC, sakshi-arora1 approved these changes

2024-04-18 04:10 UTC, merged

2024-04-18 04:45 UTC, rismehta commented
> Changes are already available in master, but the same had been reverted on 6.5 due to required changes not available in targeted Forms add-on during the release of the core-components.

Modifications to the core component should function regardless of the addon version. It's acceptable if the feature linked to addon changes doesn't work perfectly, but the form itself should render correctly.