FORMS-13810: Add the field to allow custom message for format in date…
adobe/aem-core-forms-components pull request #1158
Opened 2024-04-03 07:47 UTC by s1mahanty

… picker

## Description

## Related Issue
[FORMS-13810](https://jira.corp.adobe.com/browse/FORMS-13810)

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
When no custom message provided
<img width="1728" alt="Screenshot 2024-04-03 at 12 36 13 PM" src="https://github.com/adobe/aem-core-forms-components/assets/110378842/672a16bb-2911-4c73-971c-e0e035d25daf">

Added a field to add custom message for format

<img width="1728" alt="Screenshot 2024-04-03 at 1 10 42 PM" src="https://github.com/adobe/aem-core-forms-components/assets/110378842/c417931e-337b-4d6b-a0dc-699344125a8c">

After custom message is added
<img width="1728" alt="Screenshot 2024-04-03 at 1 10 58 PM" src="https://github.com/adobe/aem-core-forms-components/assets/110378842/5c7a5a6e-84bf-4631-850a-604b19a1fb4c">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-04-03 09:47 UTC, rismehta requested changes
Please write a runtime test case for this as part of datapicker spec so that the use-case works end to end

2024-04-04 03:46 UTC, vdua commented on ui.tests/test-module/specs/datepicker/datepicker.runtime.spec.js
> +        })
can you please add the test case where the date itself is invalid (the following values)
```
const incorrectInput = 'adfasdfa'
const incorrectInput = '29/2/2023'
const incorrectInput = '1/13/2023'
const incorrectInput = '32/1/2023'
```

Will it show the error message

2024-04-04 04:57 UTC, sakshi-arora1 commented on it/content/src/main/content/jcr_root/content/forms/af/core-components-it/samples/datepicker/basic/.content.xml
> +                    textIsRich="[true,true,true]"
this property shouldn't be there

2024-04-04 05:01 UTC, sakshi-arora1 approved these changes
Just a minor comment on collateral

2024-04-04 09:59 UTC, merged