CQ-4346472 Correct form path correlation in sling models.
adobe/aem-core-forms-components pull request #116
Opened 2022-08-12 07:07 UTC by sakshi-arora1

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2022-08-16 12:03 UTC, rismehta commented on bundles/core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormStructureParserImpl.java
> +    private static final String FORM_CONTAINER_RESOURCE_TYPE = "core/fd/components/form/container/v2/container";
We have a separate constants file for resource types, please re-use it from there.

2022-08-16 12:03 UTC, rismehta requested changes
-1 for now

2022-08-17 07:35 UTC, sakshi-arora1 commented
> -1 for now

Moved the constant.

2022-08-19 06:48 UTC, rismehta approved these changes
LGTM

2022-08-19 06:48 UTC, merged