Readonly does not work in datepicker if edit or display format set
adobe/aem-core-forms-components pull request #1165
Opened 2024-04-04 10:08 UTC by barshat7

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-04-04 15:13 UTC, dmaurya929 approved these changes

2024-04-05 04:12 UTC, sakshi-arora1 approved these changes

2024-04-05 04:57 UTC, sakshi-arora1 commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
> +            if (!this.#noFormats() && !model.getState().readOnly) {
will display format work in this case?

2024-04-05 05:13 UTC, sakshi-arora1 requested changes
Add test case for readonly date picker with display format

2024-04-05 05:18 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/js/datepickerview.js
> +            if (!this.#noFormats() && !model.getState().readOnly) {
There are multiple issuse with this,
1. readOnly can be set dynamically, so please that use-case, when readOnly would be updated at runtime updateReadOnly would be called which should enable the datePicker popup. (https://opensource.adobe.com/aem-forms-af-runtime/js-docs/classes/Field.html#readonly
2. Please use the readOnly from the model, don't use state here.

2024-04-05 05:18 UTC, rismehta requested changes
Check comments

2024-04-08 11:40 UTC, closed without merging