Removed space between the short desc if long desc is not present
adobe/aem-core-forms-components pull request #1218
Opened 2024-05-03 10:45 UTC by pavi41

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-05-03 11:00 UTC, barshat7 approved these changes

2024-05-07 07:55 UTC, rismehta commented on ui.frontend/src/view/FormFieldBase.js
> +          if (this.getTooltipDiv()) {
Can we simplify this code and make it more readable,

`function appendDescription(descriptionType) {
    if (ariaDescribedby) {
        ariaDescribedby += ` ${this.getId()}__${descriptionType}`;
    } else {
        ariaDescribedby = `${this.getId()}__${descriptionType}`;
    }
}

if (this.getTooltipDiv()) {
    appendDescription('shortdescription');
}

if (this.getErrorDiv() && this.getErrorDiv().innerHTML) {
    appendDescription('errormessage');
}`

2024-05-07 07:55 UTC, rismehta commented on ui.frontend/src/view/FormFieldBase.js
> +          if (this.getTooltipDiv()) {
Please also fix in other places, where there is code duplication

2024-05-07 07:56 UTC, rismehta requested changes
check comments

2024-05-09 06:09 UTC, sakshi-arora1 approved these changes

2024-05-09 11:25 UTC, barshat7 commented
Issue fixed in this PR
https://github.com/adobe/aem-core-forms-components/pull/1228

2024-05-09 11:25 UTC, closed without merging