Approval checkbox required by default
adobe/aem-core-forms-components pull request #1322
Opened 2024-07-18 07:06 UTC by pavi41

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-07-19 04:04 UTC, rismehta requested changes
Please add a runtime test case for the same, no PR's without test case.

2024-07-19 06:24 UTC, barshat7 commented on examples/ui.apps/src/main/content/jcr_root/apps/forms-components-examples/components/form/termsandconditions/_cq_template/.content.xml
> +    required="true"
Please add the changes in archetype proxy also
https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/adaptiveForm/termsandconditions/_cq_template.xml

2024-07-19 08:48 UTC, pavi41 commented
> Please add a runtime test case for the same, no PR's without test case.

Added test case for the same!

2024-07-23 12:16 UTC, rismehta approved these changes

2024-07-23 12:17 UTC, rismehta requested changes
You should make it required here, https://github.com/adobe/aem-core-forms-components/blob/master/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_template.xml and also in the archetype

2024-07-24 05:16 UTC, pavi41 commented
> You should make it required here, https://github.com/adobe/aem-core-forms-components/blob/master/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/termsandconditions/v1/termsandconditions/_cq_template.xml and also in the archetype

@rismehta I have added it in the file you mentioned, will create the seperate PR for archetype

2024-07-25 05:13 UTC, rismehta approved these changes

2024-07-25 05:14 UTC, merged