Fix alignment of calendar icon vertically
adobe/aem-core-forms-components pull request #1416
Opened 2024-09-23 09:31 UTC by pavi41

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-09-23 10:17 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/datepicker/v1/datepicker/clientlibs/site/css/datepickerwidget.css
> +    top: 50%;
Please add test case for this, the new cypress version also support such use-cases

2024-09-23 10:17 UTC, rismehta requested changes
check comments

2024-09-25 10:12 UTC, pavi41 commented on ui.tests/test-module/specs/datepicker/datepicker.runtime.cy.js
> +            cy.get(`#${datePicker8}`).toMatchImageSnapshot({
Created a separate test case for it.

2024-09-26 11:42 UTC, rismehta approved these changes

2024-09-26 11:42 UTC, merged