FORMS-16943: added dateToDaysSinceEpoch method
adobe/aem-core-forms-components pull request #1455
Opened 2024-10-21 07:06 UTC by arunattri26

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2024-10-21 07:31 UTC, rismehta commented on ui.frontend/package-lock.json
> +      "resolved": "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-aem-release/@aemforms/af-custom-functions/-/af-custom-functions-1.0.12.tgz",
This URL should points to npmjs

2024-10-21 10:42 UTC, arunattri26 commented on ui.frontend/package-lock.json
> +      "resolved": "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-aem-release/@aemforms/af-custom-functions/-/af-custom-functions-1.0.12.tgz",
Done.

2024-10-22 05:45 UTC, rismehta requested changes
Can you also add a test case for this use-case in this PR via visual rule editor ?

2024-10-23 05:34 UTC, arunattri26 commented
> Can you also add a test case for this use-case in this PR via visual rule editor ?

I will add it after it is merged. Since rule-editor would expect it to be present else the rule will fail. So we can't release rule-editor without this function being present in core-components.

2024-10-23 07:07 UTC, rismehta commented
> > Can you also add a test case for this use-case in this PR via visual rule editor ?
> 
> I will add it after it is merged. Since rule-editor would expect it to be present else the rule will fail. So we can't release rule-editor without this function being present in core-components.

The rule editor shouldn't rely on the core component version, as it may also fail with older versions. Please include test cases in this PR and allow them to fail until the new version of the rule editor SPA is released.

2024-10-23 12:04 UTC, arunattri26 commented
> > > Can you also add a test case for this use-case in this PR via visual rule editor ?
> > 
> > 
> > I will add it after it is merged. Since rule-editor would expect it to be present else the rule will fail. So we can't release rule-editor without this function being present in core-components.
> 
> The rule editor shouldn't rely on the core component version, as it may also fail with older versions. Please include test cases in this PR and allow them to fail until the new version of the rule editor SPA is released.

Done. I have added the tests for latest-addon and only my authoring test is failing.

2024-11-07 13:04 UTC, rismehta commented
@arunattri26 One of the test case is failing, please check and fix it

2024-11-07 13:11 UTC, arunattri26 commented
> @arunattri26 One of the test case is failing, please check and fix it

@rismehta , I checked it is failing due to old quickstart we are using in tests which does not have the latest exp-editor. After updating the QS with latest devrelease/sites-rotary branch it will get resolved.

2024-11-26 07:03 UTC, merged