CQ-4349354 - Enable Omega Tracking - For portal components
adobe/aem-core-forms-components pull request #312
Opened 2022-11-03 08:13 UTC by TalmizAhmed

## Description
Changed the `trackingFeature` string in the cq_dialog's `.content.xml` to the appropriate adaptiveform version of the string
Components affected:
- Accordion
- Title

## Related Issue
https://jira.corp.adobe.com/browse/CQ-4349354

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2022-11-03 08:54 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/title/v1/title/_cq_dialog/.content.xml
> +    extraClientlibs="[core.forms.components.title.v1.editor]"
there is no such library `core.forms.components.title.v1.editor` in the codebase.
ideally, this should come from wcm text inheritance implicitly via resourcesupertype. can you pls remove this and see if https://github.com/adobe/aem-core-wcm-components/blob/a7e377c6810dd2125a902d3ef3df5c92ec2a1719/content/src/content/jcr_root/apps/core/wcm/components/title/v2/title/clientlibs/editor/js/title.js is getting loaded in the browser while opening edit of text or not.

2022-11-03 08:57 UTC, nit23uec requested changes
inline comments.

2022-11-07 16:14 UTC, nit23uec approved these changes

2022-11-08 14:57 UTC, nit23uec commented
seems some issue with rebase.. it contains changes unrelated to this PR. pls fix.

2022-11-09 06:30 UTC, TalmizAhmed commented
@nit23uec Should be rebased properly now. Have a look

2022-11-09 12:38 UTC, nit23uec approved these changes

2022-11-09 12:38 UTC, merged