Cq 4350055 replace container components
adobe/aem-core-forms-components pull request #410
Opened 2023-01-18 21:02 UTC by egmox

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-01-19 12:00 UTC, deepprakash345 commented on ui.tests/test-module/specs/replaceaction/replacelayout.authoring.spec.js
> +    const testComponentReplaceBehaviour = function (componentEditPathSelector, componentDrop, isSites) {
can't see any test case which sends isSites argument . If we don't need it , we should remove

2023-01-20 07:02 UTC, rismehta commented
Looks like genuine test failures

2023-01-23 13:19 UTC, nit23uec commented on it/apps/src/main/content/jcr_root/apps/forms-core-components-it/clientlibs/clientlib-it-base/styles/site.css
> +.ReplaceComponentDialog-components {padding: 0;}
lets follow bem notation. css for this should be in the component rather than here.

2023-01-23 13:20 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/accordion/v1/accordion/README.md
> +## Replaceable by:
we should add more info here. here it seems that accordion is replaceable in funcitionality.

2023-01-23 13:22 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/fileinput/v1/fileinput/_cq_editConfig.xml
> +<jcr:root xmlns:granite="http://www.adobe.com/jcr/granite/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
put a condition instead in the base edit config.

2023-01-23 13:23 UTC, nit23uec commented on ui.tests/test-module/specs/replaceaction/replacelayout.authoring.spec.js
> +    // context('Open Sites Editor', function () {
this should not be commented.

2023-01-23 13:24 UTC, nit23uec requested changes
inline comments.

2023-01-30 06:06 UTC, rismehta commented
Please rebase the PR branch with latest dev branch

2023-01-30 06:06 UTC, closed without merging

2023-01-30 06:06 UTC, rismehta commented
Please rebase the PR branch latest dev branch