Cq 4351684
adobe/aem-core-forms-components pull request #483
Opened 2023-02-20 11:58 UTC by s1mahanty

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-02-21 05:29 UTC, rismehta commented on ui.frontend/src/view/FormFieldBase.js
> +                let validationMessage = LanguageUtils.getTranslatedString(this.formContainer.getModel()._jsonModel.lang, "DefaultError");
We have expose .lang so please use it directly `this.formContainer.getModel().lang`. Also, we should return a function, to make this more readable. Please check this, https://github.com/adobe/aem-core-forms-components/blob/master/ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/af-commons/v1/clientlibs/editor/utils/utils.js#L104-L124

2023-02-21 05:32 UTC, rismehta commented on ui.frontend/src/view/FormFieldBase.js
> +                let validationMessage = LanguageUtils.getTranslatedString(this.formContainer.getModel()._jsonModel.lang, "DefaultError");
Usage would be the following,
`
let getTranslatedString = LanguageUtils.getTranslatedString(this.formContainer.getModel().lang);
// create constants for all validationState
// please make the code more readable
if (ValidationStateConstants.VALUE_MISSING in validationState) {
    getTranslatedString(`${ValidationStateConstants.VALUE_MISSING}DefaultError`)
}
`

2023-02-22 10:56 UTC, rismehta commented
Please add test cases for this use-case

2023-02-22 10:58 UTC, rismehta commented
Please add test cases

2023-02-22 10:58 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/de.json
> +  "InternalFormSubmissionError" :     "Beim Übermitteln des Formulars ist ein interner Fehler aufgetreten.",
Can we match the name to the validationState, it becomes easier that way

2023-03-03 08:57 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/resources/i18n/it.json
> +  "rangeUnderflow" :                  "",
Please add english strings for all these

2023-03-03 08:58 UTC, rismehta commented on ui.frontend/src/view/FormFieldBase.js
> +                    let snippets_Array = [];
Please following the naming conventions here

2023-03-03 08:59 UTC, rismehta commented on ui.tests/test-module/specs/checkboxgroup/checkboxgroup.runtime.spec.js
> +            cy.get(`#${checkBox5}`).find(".cmp-adaptiveform-checkboxgroup__errormessage").should('have.text',"There is an error in the field.")
Please add a test case to test different error messages

2023-03-03 08:59 UTC, rismehta requested changes
-1 for now

2023-06-23 11:22 UTC, s1mahanty commented
Closing as approach changed, new changes followed up in the PR: https://github.com/adobe/aem-core-forms-components/pull/714

2023-06-23 11:22 UTC, closed without merging