FORMS-7159 title property on edit dialog of form container
adobe/aem-core-forms-components pull request #529
Opened 2023-03-07 09:20 UTC by barshat7

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-03-08 05:50 UTC, rismehta requested changes
Please add test cases

2023-03-08 05:50 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
> +                                      name="./title"/>
+1, please write a test for the same

2023-03-23 10:35 UTC, sakshi-arora1 commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TitleImpl.java
> +                title = formContainerResource.getValueMap().get("title", String.class);
why title and not jcr:title ?

2023-03-23 10:35 UTC, sakshi-arora1 approved these changes

2023-03-23 11:21 UTC, nit23uec commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
> +        if (isAFContainer(resource)) {
pls change the impl of isAFContainer to check `fieldType=form`

2023-03-23 11:23 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/_cq_dialog/.content.xml
> +                              sling:resourceType="granite/ui/components/coral/foundation/container">
pls rename the node to container rather than column as it denotes column RT

2023-03-23 14:32 UTC, nit23uec commented on ui.tests/test-module/specs/title/title.authoring.spec.js
> +            cy.wait(1000).then(() => {
avoid using wait but promises.

2023-03-23 14:32 UTC, nit23uec commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v1/form/TitleImpl.java
> +        if (StringUtils.isBlank(title)) {
how are ensuring that the title on saved on forms container when editing title component?

2023-03-31 07:36 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
> +    public static Resource getFormContainer(Resource resource) {
Please add code docs

2023-03-31 07:38 UTC, rismehta requested changes
Please add code docs

2023-04-05 07:21 UTC, rismehta approved these changes

2023-04-05 07:21 UTC, merged