Forms 2980 email tel default validaiton
adobe/aem-core-forms-components pull request #543
Opened 2023-03-21 08:54 UTC by egmox

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-03-21 08:56 UTC, egmox commented
the default validation pattern is no pattern for now which is coming from the cq-guides

<img width="551" alt="image" src="https://user-images.githubusercontent.com/18582880/226557993-82b416fc-bd72-44cc-8119-5caf3b5923ef.png">

2023-04-05 07:12 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FieldType.java
> +    EMAIL_INPUT("email-input"),
FieldType should be email, why is this email-input ?

2023-04-05 07:17 UTC, rismehta commented
Please add a runtime test case for the validation pattern in cypress

2023-04-05 07:17 UTC, rismehta requested changes
-1 for now

2023-04-05 13:45 UTC, closed without merging