FORMS-5836 - Add FastTrack Analytics support to AF2 headful
adobe/aem-core-forms-components pull request #556
Opened 2023-03-31 11:51 UTC by sauraku

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-04-03 07:08 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/js/datalayer.js
> +        const guidePath = guideBridge.getFormModel().getState().properties['fd:path'].substring(0,guideBridge.getFormModel().getState().properties['fd:path'].indexOf('/jcr:content/guideContainer'));
what is the definition of form name?
 there is no such thing as name in the schema.

2023-04-03 07:11 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/js/datalayer.js
> +        formName = _formName;
why is the field label bing passed as field name here? It is making code less readable.

2023-04-03 07:12 UTC, nit23uec commented on ui.frontend/src/view/FormFieldBase.js
> +        return this.parentView.getModel().label ? this.parentView.getModel().label.value: "Root Panel";
there is no such thing as Root Panel in the form.
we should not have have logic of getting panel title here. pls get it from event payload or introduce it at level of event payload inside guidebridge.

2023-04-03 07:13 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/af-clientlibs/core-forms-components-runtime-all/js/datalayer.js
> +    const _getEventInfo = (_eventName, _fieldName, _fieldType, _panelName,_formName ) => {
pls us `#` to denote private functions as required by ECMA6

2023-04-03 07:13 UTC, nit23uec requested changes
inline comments.

2023-04-05 06:47 UTC, sauraku commented
@nit23uec, I'll address all your concerns on this PR: https://github.com/adobe/aem-core-forms-components/pull/557
Merging https://github.com/adobe/aem-core-forms-components/pull/557 and https://github.com/adobe/aem-core-forms-components/pull/556 into single PR.
closing this PR.

2023-04-05 06:47 UTC, closed without merging