FORMS-2980: synced fieldType email with af2-web-runtime
adobe/aem-core-forms-components pull request #562
Opened 2023-04-05 13:28 UTC by egmox

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-04-05 16:06 UTC, nit23uec commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_template.xml
> +    jcr:title="Email Input"/>
just `Email` in the title is enough.

2023-04-05 18:35 UTC, barshat7 commented
We will need to update the fieldType in archetype also https://github.com/adobe/aem-project-archetype/blob/ff01ddb5ffc86b597e46d7daa69d75d22775187c/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/adaptiveForm/emailinput/_cq_template.xml#L5
@egmox  Please raise a Jira for this.

2023-04-06 04:30 UTC, nit23uec approved these changes

2023-04-06 06:44 UTC, rismehta commented on ui.frontend/package.json
> +    "@aemforms/af-core": "0.22.38",
You need to add ^ here

2023-04-06 06:45 UTC, rismehta commented on ui.tests/test-module/specs/emailinput/emailinput.authoring.spec.js
> +      getPreviewIframeBody().find('.cmp-adaptiveform-emailinput__errormessage').should('exist');
This test needs to be written in emailinput.runtime.spec.js. Let's not access iframe details inside authoring

2023-04-06 06:45 UTC, rismehta requested changes
-1 for now

2023-04-06 08:58 UTC, egmox commented
@rismehta resolved the comments

2023-04-06 10:57 UTC, rismehta approved these changes
LGTM

2023-04-06 10:57 UTC, merged