FORMS-8029 - Static Text Core Component should update value via Rules
adobe/aem-core-forms-components pull request #659
Opened 2023-05-23 09:49 UTC by TalmizAhmed

## Description
https://jira.corp.adobe.com/browse/FORMS-8029

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-05-23 09:56 UTC, deepprakash345 commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/js/textview.js
> +                let actualValue = typeof value === "undefined" ? null :  value;
in what scenario will we get undefined as value from model ?
Also if the value is undefined? is putting null recommended or should we put an empty string?will it cause any difference in behaviour?

2023-05-23 14:12 UTC, rismehta requested changes
Please add a test case for this use-case

2023-05-24 02:50 UTC, deepprakash345 commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/text/v1/text/clientlibs/site/js/textview.js
> +            updateValue(value) {
Can you add a cypress test to verify this behaviour

2023-05-25 09:17 UTC, deepprakash345 requested changes

2023-05-25 10:04 UTC, TalmizAhmed commented on ui.tests/test-module/specs/text/text.runtime.spec.js
> +    it.only('test the rules editor', () => {
My bad

2023-05-26 09:20 UTC, rismehta approved these changes

2023-05-26 09:20 UTC, merged