Dropdown / Checkbox Group / Radiobutton list does not maintain order on UI
adobe/aem-core-forms-components pull request #704
Opened 2023-06-14 11:47 UTC by amanthakur03

2023-06-14 13:49 UTC, rismehta commented on bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/DropDownImplTest.java
> -import java.util.Map;
Please fix the imports

2023-06-14 13:49 UTC, rismehta commented on bundles/af-core/src/test/java/com/adobe/cq/forms/core/components/internal/models/v1/form/RadioButtonImplTest.java
> +import java.util.*;
Please fix the imports everywhere

2023-06-15 05:40 UTC, barshat7 commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractOptionsFieldImpl.java
> +    private LinkedHashMap<Object, String> removeDuplicates() {
Ideally you should return/accept an interface. No need to change the signature.

2023-06-15 12:18 UTC, barshat7 commented
LGTM

2023-06-15 12:19 UTC, barshat7 approved these changes

2023-06-15 12:42 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractOptionsFieldImpl.java
> +        Preconditions.checkNotNull(enumArray, "Variable must not be null");
Also, I prefer null checks makes the code more readable and self-documenting by clearly expressing the intent that a certain value should not be null.

2023-06-15 12:42 UTC, rismehta requested changes
-1 for now

2023-06-16 08:27 UTC, merged