Forms 9330 checkbox
adobe/aem-core-forms-components pull request #717
Opened 2023-06-26 06:50 UTC by barshat7

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-06-29 06:23 UTC, devgurjar reviewed
Please update year at multiple places.
Please validate DoR generation for this component.

2023-06-29 06:23 UTC, devgurjar commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/README.md
> +Copyright 2022 Adobe
update year

2023-06-29 06:23 UTC, devgurjar commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/_cq_dialog/.content.xml
> +  ~ Copyright 2022 Adobe
update year

2023-06-29 06:23 UTC, devgurjar commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/checkbox/v1/checkbox/checkbox.html
> +  ~ Copyright 2022 Adobe
Update year

2023-07-05 06:46 UTC, devgurjar approved these changes
LGTM

2023-07-06 08:36 UTC, rismehta requested changes
check comments

2023-07-07 09:22 UTC, merged