FORMS-10259 - Custom properties - Refactor code to new design aligning to styles
adobe/aem-core-forms-components pull request #812
Opened 2023-08-09 12:24 UTC by TalmizAhmed

Jira: https://jira.corp.adobe.com/browse/FORMS-10259

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-08-14 10:15 UTC, rismehta requested changes
-1 for now

2023-08-14 10:15 UTC, rismehta commented on bundles/af-core/pom.xml
> +        <dependency>
You only need to access the API's via the uber aem forms SDK.

2023-08-14 10:15 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/form/FormConstants.java
> +    public static final String PN_CUSTOM_PROPERTY_ADDITIONAL_KEYS = "fd:additionalCustomPropertyKeys";
These properties should still not be required, you need to directly access it via cq-guides, since cq-guides own these properties

2023-08-14 10:15 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractComponentImpl.java
> +            this.id = com.adobe.cq.wcm.core.components.util.ComponentUtils.getId(this.resource, this.currentPage, resourceCallerPath,
Please remove the changes which are not required, please mark the PR for review only if it is ready

2023-08-14 12:04 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
> +            PN_CUSTOM_PROPERTY_ADDITIONAL_VALUES)) {
Why is this logic required here ? Ideally core component should not use these property names

2023-08-18 05:38 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
> +import com.adobe.aemds.guide.model.impl.CustomPropertyInfoImpl;
How will implementation be accessible here ?

2023-08-18 05:38 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/AbstractFormComponentImpl.java
> +        return Optional.ofNullable(this.resource.adaptTo(CustomPropertyInfoImpl.class))
You need to adapt to the interface here

2023-08-18 05:39 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormComponent.java
> +    public final String CUSTOM_LAYOUT_PROPERTY_WRAPPER = "afs:layout";
You can't rename a public constant

2023-08-18 05:39 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/util/ComponentUtils.java
> +    public static <T> T[] convertToArray(T param) {
Why is this change required, this is not used anywhere, please revert unrequired changes and raise a PR

2023-08-18 05:39 UTC, rismehta requested changes
-1 for now

2023-08-21 05:59 UTC, TalmizAhmed commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/models/form/FormComponent.java
> +    public final String CUSTOM_LAYOUT_PROPERTY_WRAPPER = "afs:layout";
Reverting

2023-08-21 09:09 UTC, TalmizAhmed commented
Creating new PR, closing this one

2023-08-21 09:09 UTC, closed without merging