FORMS-9362: loading icon behind fields
adobe/aem-core-forms-components pull request #880
Opened 2023-09-18 11:27 UTC by AnurudraS

## Description

As discussed with Rishi, the sibling div should have the selector as the ID of form and selecting the div with the same and adding the loading class on it later removing as well with the same steps.
However the test cases were already written in command.js file therefore, I have made the corrections in the same for the updated logic.
the new updates has been added to the readme file as well.

## Related Issue
FORMS-9362: Loading Icon Behind Fields

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

2023-09-18 14:55 UTC, AnurudraS commented
Test cases were already present in command.js therefore, I have updated the test case according to the latest code.

2023-09-18 14:55 UTC, AnurudraS commented on ui.tests/test-module/libs/support/commands.js
Test cases were already present in command.js therefore, I have updated the test case according to the latest code.

2023-09-21 09:04 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +            loaderToAdd.classList.add(FormContainerV2.loadingClass);
Please add a null check here, 

if (loaderToAdd) {
     loaderToAdd.classList.add(FormContainerV2.loadingClass);
}

2023-09-21 09:04 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +                let loaderToRemove = document.querySelector("[data-cmp-adaptiveform-container-loader='"+ formEl.id + "']");
Also add a safe check here

2023-09-21 09:04 UTC, rismehta requested changes
check changes

2023-09-21 10:33 UTC, AnurudraS commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +            loaderToAdd.classList.add(FormContainerV2.loadingClass);
added!

2023-09-21 10:33 UTC, AnurudraS commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +                let loaderToRemove = document.querySelector("[data-cmp-adaptiveform-container-loader='"+ formEl.id + "']");
added!

2023-09-22 07:40 UTC, rismehta requested changes
Please write a test case for the fix

2023-09-27 09:49 UTC, AnurudraS commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +            if(loaderToAdd){
done.

2023-09-27 11:15 UTC, merged