[RTL] Change direction of content in forms at runtime
adobe/aem-core-forms-components pull request #885
Opened 2023-09-25 09:14 UTC by devgurjar

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-09-25 09:51 UTC, sakshi-arora1 commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +            if (formLanguage) {
before setting it check if "dir" is already set at body

2023-09-25 11:26 UTC, sakshi-arora1 approved these changes

2023-09-26 10:42 UTC, devgurjar commented
One test is failing in CI, but passing locally.

2023-09-29 05:39 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
> +        if (StringUtils.isNotEmpty(language)) {
String language = getLang();
return Arrays.stream(new String[] {"ar", "iw", "he", "fa", "ur", "ug", "ji", "yi"})
    .anyMatch(lang -> lang.equalsIgnoreCase(language.split("-")[0]));

2023-09-29 05:40 UTC, rismehta commented on bundles/af-core/src/main/java/com/adobe/cq/forms/core/components/internal/models/v2/form/FormContainerImpl.java
> +        if (isLangRTL()) {
Can you create something in ComponentUtils for this, 

`ComponentUtils.getLanguageDirection` and move the entire logic there

2023-09-29 05:41 UTC, rismehta requested changes
Please don't raise a PR without unit test cases. Thanks.

2023-09-29 05:41 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/container/v2/container/clientlibs/site/js/formcontainerview.js
> +//            if (formContainer._element && !formContainer._element.dir && formLanguage) {
Please remove this, not sure why is it commented, let's keep the code source clean

2023-09-29 05:55 UTC, devgurjar commented
Closing this PR

2023-09-29 05:55 UTC, closed without merging