embed dependency as part of all.zip so that it does not conflict with…
adobe/aem-core-forms-components pull request #914
Opened 2023-10-09 12:47 UTC by barshat7

… archetype project

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-10-09 12:50 UTC, rismehta requested changes
Please write test case for the same

2023-10-25 06:53 UTC, barshat7 commented
> Please write test case for the same

Test cases were there but the example was also pointing to wcm foundation that's why it was not able to detect. Updated the examples component also so that test is executed on correct component

2023-10-25 09:24 UTC, sakshi-arora1 approved these changes

2023-10-25 14:24 UTC, sakshi-arora1 approved these changes

2023-10-25 14:24 UTC, merged