Add autocomplete attribute on input and fix placeholder property.
adobe/aem-core-forms-components pull request #955
Opened 2023-10-27 06:04 UTC by dmaurya929

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [ ] All unit tests pass on CircleCi.
- [ ] I ran all tests locally and they pass.

2023-10-27 08:46 UTC, rismehta commented on ui.af.apps/src/main/content/jcr_root/apps/core/fd/components/form/emailinput/v1/emailinput/_cq_dialog/.content.xml
> +                                                    wrapperClass="cmp-adaptiveform-textinput__autofillfieldkeyword"
this is email input `cmp-adaptiveform-emailinput`

2023-10-27 08:48 UTC, rismehta commented on ui.frontend/package-lock.json
> +      "requires": {}
Can you revert the changes in this file ?

2023-10-27 08:48 UTC, rismehta requested changes
check comments

2023-11-02 11:03 UTC, dmaurya929 commented
@sakshi-arora1 please review this PR.

2023-11-06 09:58 UTC, sakshi-arora1 approved these changes

2023-12-12 13:23 UTC, merged